--DELETE FROM SERVICE_PROVIDER;

DROP TABLE IF EXISTS SERVICE_PROVIDER;
  
CREATE TABLE SERVICE_PROVIDER (
  SERVICE_PROVIDER_ID 		INT 			AUTO_INCREMENT  PRIMARY KEY,
  SERVICE_PROVIDER_NAME 	VARCHAR(250) 	NOT NULL,
  PHONE_NO 					VARCHAR(250) 	NOT NULL,
  EMAIL_ID 					VARCHAR(250) 	NOT NULL,
  SERVICE_ID 				VARCHAR(250) 	NOT NULL,
  PINCODE 					INT			 	NOT NULL
);